Repository nnstreamer/TAOS-CI, pull requests merged in 2018-10, with the labels that each got.

#282 Fix typo in server manual
  ci/doc/how-to-setup-taos-ci-server.md
Labels: Hacktoberfest, bug

#281 slocc: add .sh and .php to append a source range
  ci/taos/plugins-good/pr-format-sloccount.sh
  ci/taos/webapp/install-packages.sh
Labels: Hacktoberfest

#288 Doc: Requirement for merging new CI module
  ci/doc/how-to-use-taos-ci-module.md
Labels: Hacktoberfest, documentation

#291 slocc: fixed indentation of slocc module
  ci/taos/plugins-good/pr-format-sloccount.sh
Labels: Hacktoberfest, bug

#290 Module: Added prohibited words facility
  ci/taos/config/config-plugins-format.sh
  ci/taos/config/prohibited_words.txt
  ci/taos/plugins-good/pr-format-prohibited-words.sh
Labels: Hacktoberfest, priority-low

#300 Webhook handler: Unified two checkers (format and audit) @open sesame 10/16 19:09
  ci/taos/checker-pr-gateway.sh
  ci/taos/webhook.php
Labels: Hacktoberfest, enhancement

#305 PR-gateway: run git command just once
  ci/taos/checker-pr-audit-async.sh
  ci/taos/checker-pr-format-async.sh
  ci/taos/checker-pr-gateway.sh
Labels: Hacktoberfest, enhancement, feature

#312 DOC: fix a typo in README.md
  README.md
Labels: Hacktoberfest

#325 PR #1
  README.md
Labels: Hacktoberfest

#328 PR #4
  README.md
Labels: Hacktoberfest

#329 PR #5
  README.md
Labels: Hacktoberfest

#326 PR #2
  README.md
Labels: Hacktoberfest

#327 PR #3
  README.md
Labels: Hacktoberfest

#324 prtest1
  ci/doc/coding-convention.md
Labels: Hacktoberfest

#357 Debian: fixed a not compatible version number - @open sesame 10/26 11:27
  debian/changelog
Labels: Hacktoberfest, bug, enhancement

#358 Update coding-convention.md
  ci/doc/coding-convention.md
Labels: Hacktoberfest, documentation

#359 Update doxygen-documentation.md
  ci/doc/doxygen-documentation.md
Labels: Hacktoberfest, documentation

#360 Update how-to-archive-large-data.md
  ci/doc/how-to-archive-large-data.md
Labels: Hacktoberfest, documentation

#361 Update how-to-build-gbs-pdebuild.md
  ci/doc/how-to-build-gbs-pdebuild.md
Labels: Hacktoberfest, documentation
